function [Rsq2,AICc] =  R2_AICc(p,Valid_set,data,scale_id,kfixed)

global Measure_Inds time_daps FDA_add_idxs x0s int_times exp_temps

%Introduction of normal error variation 5%
This_it_KM  = data;

%Integration times based on point after dap addition
t1          = int_times{Valid_set,scale_id}(int_times{Valid_set,scale_id}<time_daps{Valid_set,scale_id});
t2          = int_times{Valid_set,scale_id}(int_times{Valid_set,scale_id}>=time_daps{Valid_set,scale_id});

%Integration options
options = odeset('RelTol',1e-3,'AbsTol',1e-3);

%Pre DAP addition section
[T1,X1]   = ode45(@Zenteno_Model_2020_PEVth9_2023,t1,x0s{Valid_set,scale_id},options,p,int_times{Valid_set,scale_id},exp_temps{Valid_set,scale_id},kfixed);
x02       = X1(end,:);  x02(2) = This_it_KM(FDA_add_idxs{Valid_set,scale_id},4)/1000;

%After DAP addition section
[T2,X2]   = ode45(@Zenteno_Model_2020_PEVth9_2023,t2,x02,options,p,int_times{Valid_set,scale_id},exp_temps{Valid_set,scale_id},kfixed);

%Resulting data consolidation
T         = [T1;T2];
X         = [X1;X2];

%Target points selection
X         = X(ismember(T,int_times{Valid_set,scale_id}),:);            %We eliminate extra points generated by integration
total_idx = (1:1:length(X))';
X_sim     = X(ismember(total_idx,Measure_Inds{Valid_set,scale_id}),:); %X_sim contains the simulated points equivalent to those experimentally measured.

%Data definition
N_data = This_it_KM(:,4);                              N_sim = X_sim(:,2).*1000;                                                                                      %N_pond    = 1/(sum(Kinetic_Matrixes{i,scale_id}(1:FDA_add_idxs{i,scale_id}+1,4))/sum(Kinetic_Matrixes{i,scale_id}(:,3))); %This ponderator will weigth up N adjust to the same level as S related error.
G_data = This_it_KM(:,1);                              G_sim = X_sim(:,3);
F_data = This_it_KM(:,2);                              F_sim = X_sim(:,4);

% Calcular R^2 para cada estado

% Residuos del estado 1
residuals1 = N_data - N_sim;  
SSR1 = sum(residuals1.^2);
Rsq_N = 1 - SSR1 / sum((N_data - mean(N_sim)).^2);

% Residuos del estado 2
residuals2 = G_data - G_sim;  
SSR2 = sum(residuals2.^2);
Rsq_G = 1 - SSR2 / sum((G_data - mean(G_data)).^2);

% Residuos del estado 3
residuals3 = F_data - F_sim;  
SSR3 = sum(residuals3.^2);
Rsq_F = 1 - SSR3 / sum((F_data - mean(F_data)).^2);

% Calcular R^2 ajustado para cada estado
R2adj_N = 1 - ((1 - Rsq_N) * (length(N_data) - 1) / (length(N_data) - length(p) - 1));
R2adj_G = 1 - ((1 - Rsq_G) * (length(G_data) - 1) / (length(G_data) - length(p) - 1));
R2adj_F = 1 - ((1 - Rsq_F) * (length(F_data) - 1) / (length(F_data) - length(p) - 1));

Rsq2_adj   = [R2adj_N;R2adj_G;R2adj_F];
Rsq2       = [Rsq_N;Rsq_G;Rsq_F];
%AIC & BIC calculations:
SS    = sum([SSR1,SSR2,SSR3]);
m     = length(p);
[N,~] = size([residuals1;residuals2;residuals3]);
AIC   = N*log(SS/N)+2*(m+1);
AICc  = AIC + 2*(m+1)*(m+2)/(N-m-2);

end




