function dx0dthSym = dICdthZenteno(in1,in2)
%dICdthZenteno
%    dx0dthSym = dICdthZenteno(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Apr-2026 23:15:27

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,9]);
end
