function x0Sym = x0Zenteno(in1)
%x0Zenteno
%    x0Sym = x0Zenteno(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Apr-2026 23:15:27

x0Sym = [1.0./5.0;1.736666666666667e-1;1.1555e+2;1.0094e+2;0.0];
end
