%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% obj_func
% Integrates the dynamic model and calculates afterwards the cuadratic 
% difference between the model predictions and the experimental data,
% normalized by the maximum value of the experimental data. Returns the
% cuadratic difference (objective function). To be used in the parameter
% estimation with SSm.
%
% Benjamín J. Sánchez
% Last Update: 2013-06-07
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [J,g,R]=obj_func(k,~,~)
global int_time time_dap  Kinetic_Matrix x0 FDA_add_idx Measure_Ind

%Integration times based on point after dap addition
t1        = int_time(int_time<time_dap);
t2        = int_time(int_time>=time_dap);

%Integration options
options = odeset('RelTol',1e-3,'AbsTol',1e-3);

%Pre DAP addition section
[T1,X1]   = ode23t(@model,t1,x0,options,k);
x02       = X1(end,:);  x02(2) = Kinetic_Matrix(FDA_add_idx,4)/1000;

%After DAP addition section
[T2,X2]   = ode23t(@model,t2,x02,options,k);

%Resulting data consolidation
T         = [T1;T2];
X         = [X1;X2];

%Target points selection
X         = X(ismember(T,int_time),:);            %We eliminate extra points generated by integration
total_idx = (1:1:length(X))';
X_sim     = X(ismember(total_idx,Measure_Ind),:); %X_sim contains the simulated points equivalent to those experimentally measured.

%error(i)  = sum(sum((X_sim(1:FDA_add_idxs{i,j}+1,2).*1000-Kinetic_Matrixes{i,j}(1:FDA_add_idxs{i,j}+1,4)).^2)*N_pond + sum(((X_sim(:,3)-Kinetic_Matrixes{i,j}(:,1))).^2)+ sum(((X_sim(:,4)-Kinetic_Matrixes{i,j}(:,2))).^2)); %Error function

if length(X_sim(:,2)) == length(Kinetic_Matrix(:,4))
    
    %Data definition
    G_data                  = Kinetic_Matrix(:,1);                       G_sim                  = X_sim(:,3);
    F_data                  = Kinetic_Matrix(:,2);                       F_sim                  = X_sim(:,4);
    N_data                  = zeros(size(G_data));                       N_sim                  = zeros(size(G_data));
    N_data(1:FDA_add_idx+1) = Kinetic_Matrix(1:FDA_add_idx+1,4);         N_sim(1:FDA_add_idx+1) = X_sim(1:FDA_add_idx+1,2).*1000;                                                                                      %N_pond    = 1/(sum(Kinetic_Matrixes{i,j}(1:FDA_add_idxs{i,j}+1,4))/sum(Kinetic_Matrixes{i,j}(:,3))); %This ponderator will weigth up N adjust to the same level as S related error.

    %Construction of residual matrix:
    R    = [(N_data-N_sim)./max(N_data) (G_data-G_sim)./max(G_data) (F_data-F_sim)./max(F_data)]; 
    
    %Calculation of the objective function:
    J = sum(sum(R.^2)); %disp(['J = ' num2str(J)]);
    g = 0;
    R=reshape(R,numel(R),1);

else
    R    = NaN;
    J    = NaN;
    g    = NaN;
end
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%