%------------------------Cross-Validation problem-----------------%

function Total_Error = CrossValidationCalibrationZ(p,Combinations,Scale_Experiments,scale_id,kfixed)

global Measure_Inds time_daps FDA_add_idxs Kinetic_Matrixes x0s int_times exp_temps

for s = 1:Scale_Experiments-2

    parfor n = 1:size(Combinations{s},1)

        for k = 1:size(Combinations{s},2)

            i = Combinations{s}(n,k);

            %Integration times based on point after dap addition
            t1        = int_times{i,scale_id}(int_times{i,scale_id}<time_daps{i,scale_id});
            t2        = int_times{i,scale_id}(int_times{i,scale_id}>=time_daps{i,scale_id});

            %Integration options
            options = odeset('RelTol',1e-3,'AbsTol',1e-3);

            % Pre/Post DAP integration (robust when one segment is empty).
            T1 = []; X1 = [];
            T2 = []; X2 = [];
            if numel(t1) >= 2
                [T1,X1] = ode15s(@Zenteno_Model_2020_PEV,t1,x0s{i,scale_id},options,p,int_times{i,scale_id},exp_temps{i,scale_id},kfixed);
            elseif numel(t1) == 1
                T1 = t1(:);
                X1 = x0s{i,scale_id};
            end

            idx_dap = FDA_add_idxs{i,scale_id};
            if isempty(X1)
                x02 = x0s{i,scale_id};
            else
                x02 = X1(end,:);
            end
            x02(2) = max(Kinetic_Matrixes{i,scale_id}(idx_dap,4),0)/1000;

            if numel(t2) >= 2
                [T2,X2] = ode15s(@Zenteno_Model_2020_PEV,t2,x02,options,p,int_times{i,scale_id},exp_temps{i,scale_id},kfixed);
            elseif numel(t2) == 1
                T2 = t2(:);
                X2 = x02;
            end

            %Resulting data consolidation
            T         = [T1;T2];
            X         = [X1;X2];


            %Target points selection
            X         = X(ismember(T,int_times{i,scale_id}),:);            %We eliminate extra points generated by integration
            total_idx = (1:1:length(X))';
            X_sim     = X(ismember(total_idx,Measure_Inds{i,scale_id}),:); %X_sim contains the simulated points equivalent to those experimentally measured.

            if length(X_sim(:,3)) == length(Kinetic_Matrixes{i,scale_id}(:,1))

                %Data definition
                N_data = Kinetic_Matrixes{i,scale_id}(1:FDA_add_idxs{i,scale_id}+1,4);   N_sim = X_sim(1:FDA_add_idxs{i,scale_id}+1,2).*1000;
                G_data = Kinetic_Matrixes{i,scale_id}(:,1);              G_sim = X_sim(:,3);
                F_data = Kinetic_Matrixes{i,scale_id}(:,2);              F_sim = X_sim(:,4);

                %Error function - Ponderation by the highest error
                %                                   Nitrogen Error                Glucose Error                         Fructose Error
                error(n) = sum(sum(((N_data-N_sim)./max(N_data)).^2)/length(N_data) + sum(((G_data-G_sim)./max(G_data)).^2)/length(G_data) + sum(((F_data-F_sim)./max(F_data)).^2)/length(F_data));

            else
                error(n) = NaN;
            end
        end
    end

    ERROR(s)    = sum(error);

end
Total_Error     = sum(ERROR);

end
